### ISSUE TITLE
Grammata executable doesn't work.

### ISSUE THREAD

**Issue by daantjie** [jgm/grammata#1]
```
$ stack install
$ export GHC_PACKAGE_PATH=`stack path --snapshot-pkg-db`
$ grammata TeX test.gram
/tmp/1485982968849681594153:6:1: error:
    Failed to load interface for ‘Prelude’
    Use -v to see a list of the files searched for.
```
[Arch Linux]

**Comment by jgm** [comment]
You need the colon after `stack path --snapshot-pkg-db`:

    export GHC_PACKAGE_PATH=`stack path --snapshot-pkg-db`:

Also, use `grammata LaTeX` instead of `grammata TeX`.  (I'll
fix this in the README.)

+++ Daniel Oosthuizen [Oct 04 17 16:51 ]:
